siguetufuncionario/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from funcionarios.views import FuncionariosListView,DenunciasListView, FuncionarioDetailView, TareaDetailView,DenunciaCreate
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'siguetufuncionario.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    #url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^$', FuncionariosListView.as_view()),  
    url(r'^guarda_like/', 'funcionarios.views.guarda_like'),
    url(r'^cuenta_like/', 'funcionarios.views.cuenta_like'),
    url(r'^guarda_like_tarea/', 'funcionarios.views.guarda_like_tarea'),
    url(r'^cuenta_like_tarea/', 'funcionarios.views.cuenta_like_tarea'),    
    url(r'^logout/$', 'base.views.logout'),  
    #url(r'^ficha/', TemplateView.as_view(template_name="ficha.html")),
    url(r'^ficha/(?P<pk>[\d]+)', FuncionarioDetailView.as_view()),
    url(r'^denuncias/(?P<pk>[\d]+)', TareaDetailView.as_view()),
    url(r'^lista_denuncias/(?P<pk>[\d]+)', DenunciasListView.as_view()),
    url(r'^denuncia_create/', DenunciaCreate.as_view()),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models

# Create your models here.

funcionarios/models.py
from django.db import models
from cuser.fields import CurrentUserField

class Dependencia(models.Model):
	nombre=models.CharField(max_length=300)

	def __unicode__(self):
		return self.nombre

# Create your models here.
class Funcionario(models.Model):
	nombre=models.CharField(max_length=300)
	puesto=models.CharField(max_length=300)
	domicilio=models.CharField(max_length=500)
	telefonos=models.CharField(max_length=150)
	correo=models.CharField(max_length=150)	
	fotografia = models.ImageField(upload_to='fotografias')
	dependencia = models.ForeignKey(Dependencia)
	def __unicode__(self):
		return self.nombre 

class FuncionarioMeGusta(models.Model):
	funcionario = models.ForeignKey(Funcionario)	
	usuario = CurrentUserField(related_name="usuario_fb")
	megusta=models.BooleanField(default=False)		
	def __unicode__(self):
		return str(self.usuario.id)

class Estado(models.Model):
	estado=models.CharField(max_length=50)
	def __unicode__(self):
		return self.estado 

class Tarea(models.Model):	
	meta=models.TextField()
	resultado=models.TextField(null=True, blank=True)
	imagen = models.ImageField(upload_to="resultados", blank=True, null=True)
	fecha = models.DateTimeField(auto_now_add=True, blank=True)
	funcionario = models.ForeignKey(Funcionario)
	estado = models.ForeignKey(Estado)
	def __unicode__(self):
		return self.meta	

class TareaMeGusta(models.Model):
	tarea = models.ForeignKey(Tarea)	
	usuario = CurrentUserField()
	megusta=models.BooleanField(default=False)		
	def __unicode__(self):
		return str(self.usuario.id)

class Denuncia(models.Model):
	tarea = models.ForeignKey(Tarea)	
	usuario = CurrentUserField()
	denuncia=models.TextField()
	fecha = models.DateTimeField(auto_now_add=True, blank=True)

	class Meta:
		ordering = ["-fecha"]

	def __unicode__(self):
		return self.denuncia	

base/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import logout as auth_logout
# Create your views here.
def login(request):
    # context = RequestContext(request, {
    #     'request': request, 'user': request.user})
    # return render_to_response('login.html', context_instance=context)
	return render(request, 'index.html')

def logout(request):
	auth_logout(request)
	return redirect('/')

base/templates/denuncias.html
<!doctype html>
<!--
  Material Design Lite
  Copyright 2015 Google Inc. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License
-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sigue a tu Funcionario</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="images/touch/chrome-touch-icon-192x192.png">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">
    <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">

    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
    <!--
    <link rel="canonical" href="http://www.example.com/">
    -->

    <link href='//fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link rel="stylesheet" href="{{STATIC_URL}}md/material.grey-orange.min.css">
    <link rel="stylesheet" href="{{STATIC_URL}}md/styles.css">
    <link rel="stylesheet" href="{{STATIC_URL}}stylesheets/app.css">
  </head>
  <body>
    <div class="demo-blog demo-blog--blogpost mdl-layout mdl-js-layout has-drawer is-upgraded">
      {% if user and user.is_anonymous %}                       
      <div class="android-wear-band">
        <div class="android-wear-band-text">
          <br>
          <p>            
            <a href="{% url 'social:begin' 'facebook' %}" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect  entra-facebook ">
              Entrar con Facebook
            </a>
            <a href="{% url 'social:begin' 'twitter' %}" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect  entra-twitter ">
              Entrar con Twitter
            </a>   
            
          </p>
        </div>
      </div>
      {% endif %}     
      <main class="mdl-layout__content">
        <div class="demo-back">
          <a class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" href="/ficha/{{tarea.funcionario.id}}" title="go back" role="button">
            <i class="material-icons" role="presentation">arrow_back</i>
          </a>
        </div>
        <div class="demo-blog__posts mdl-grid">
          <div class="mdl-card mdl-shadow--4dp mdl-cell mdl-cell--12-col">
            <div class="mdl-card__media mdl-color-text--grey-50" style="position:relative;">              
              <img src="{{MEDIA_URL}}{{tarea.funcionario.fotografia}}"  class="avatar">            

              <h3 style="padding:10px;margin-left: auto; margin-right: auto;">{{tarea.funcionario.nombre}}</h3>
            </div>

            
            <div class="mdl-color-text--grey-700 mdl-card__supporting-text meta" style="padding: 0px;min-height:1px;">
            </div>
            
            <div class="mdl-color-text--grey-700 mdl-card__supporting-text">
                 
                <div class="demo-blog__posts mdl-grid">
                                 
                    <div class="mdl-card mdl-cell mdl-cell--12-col  mdl-shadow--2dp "  style="min-height:0px;">
                      <div class="mdl-card__supporting-text" style="background-color: #ECECEC;">
                        <h5 class="titulo-card">{{tarea.meta}}</h5>
                      </div>

                      <div class="mdl-card__supporting-text">
                        {% if tarea.estado.id == 1 %}  
                        <i class="material-icons" >alarm</i> 
                        {% else %}
                        <i class="material-icons" >done</i> 
                        {% endif %}
                        
                        {{tarea.estado}}                          
                      </div>

                      {% if tarea.resultado %}
                      <div class="mdl-color-text--grey-600 mdl-card__supporting-text">
                        <span class="negrita">Resultados:</span> {{tarea.resultado}}            
                      </div>                      
                      <div class="mdl-color-text--grey-600 mdl-card__supporting-text">
                      {% if tarea.imagen %}
                        <img src="{{MEDIA_URL}}{{tarea.imagen}}" style="width:300px;">                         
                      {% endif %}                                
                      </div>
                      {% endif %}                      

                      <div class="meta mdl-card__supporting-text mdl-color-text--grey-600" style="font-size: 13px;">
                        
                        <div class="section-spacer"></div>                
                        {% if user and not user.is_anonymous %}    

                        {% if like != None %}                     
                        {% if like == True %}              
                        <span class="texto-megusta" id="cuantomegusta{{tarea.id}}">{{megusta}}</span> <button class="megusta_tarea like-azul right" like="1" idtarea="{{tarea.id}}" id="megusta{{tarea.id}}" ><i class="material-icons">thumb_up</i>  </button>                           
                        <span class="texto-megusta" id="cuantonomegusta{{tarea.id}}">{{nomegusta}}</span> <button class="megusta_tarea dislike right" like="0" idtarea="{{tarea.id}}" id="nomegusta{{tarea.id}}" ><i class="material-icons">thumb_down</i>  </button>                  
                        {% else %}                        
                        <span class="texto-megusta" id="cuantomegusta{{tarea.id}}">{{megusta}}</span> <button class="megusta_tarea like right" like="1" idtarea="{{tarea.id}}" id="megusta{{tarea.id}}" ><i class="material-icons">thumb_up</i></button>                        
                        <span class="texto-megusta" id="cuantonomegusta{{tarea.id}}">{{nomegusta}}</span> <button class="megusta_tarea dislike-rojo right" like="0" idtarea="{{tarea.id}}" id="nomegusta{{tarea.id}}" ><i class="material-icons">thumb_down</i> </button> 
                        {% endif %}
                        {% else%}            
                        <span class="texto-megusta" id="cuantomegusta{{tarea.id}}">{{megusta}}</span> <button class="megusta_tarea like right" like="1" idtarea="{{tarea.id}}" id="megusta{{tarea.id}}"><i class="material-icons">thumb_up</i></button>                        
                        <span class="texto-megusta" id="cuantonomegusta{{tarea.id}}">{{nomegusta}}</span> <button class="megusta_tarea dislike right" like="0" idtarea="{{tarea.id}}" id="nomegusta{{tarea.id}}"><i class="material-icons">thumb_down</i></i>  </button>     
                        {% endif %}

                        {% else %}   
                        <span class="texto-megusta">{{megusta}}</span> <button class="like right" onclick="javascript:alert('Identificate!!');"><i class="material-icons">thumb_up</i> </button>
                        <span class="texto-megusta">{{nomegusta}}</span> <button class="dislike right" onclick="javascript:alert('Identificate!!');"><i class="material-icons">thumb_down</i></button>          
                        
                        {% endif %}                          
                      </div>
                         
                    </div>                                           
                  
                    </div>
            </div>
            <div class="mdl-color-text--primary-contrast mdl-card__supporting-text comments">
              <input type="hidden" id="idtarea" value="{{tarea.id}}">
              {% if user and not user.is_anonymous %}   
              <form id="frmDenuncia">
                <input type="hidden" name="tarea" id="id_tarea" value="{{tarea.id}}">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                  {{form.denuncia}}
                  <label for="comment" class="mdl-textfield__label"><img src="{{user.profile.photo}}" class="img-profile" > Escribe tu denuncia ... </label>
                </div>
                
                <button id="add_denuncia" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
                Agregar
                </button>              
              </form>
              {%else%}
              <p class="negrita">Entra con Facebook o Twitter para poder agregar tu denuncia.</p>
              {%endif%}
              <div id="lista_denuncias"></div>
              
            </div>
          </div>


        </div>
        <footer class="mdl-mini-footer">
          <div class="mdl-mini-footer--left-section">
            <button class="mdl-mini-footer--social-btn social-btn social-btn__twitter">
              <span class="visuallyhidden">Twitter</span>
            </button>
            <button class="mdl-mini-footer--social-btn social-btn social-btn__blogger">
              <span class="visuallyhidden">Facebook</span>
            </button>
            <button class="mdl-mini-footer--social-btn social-btn social-btn__gplus">
              <span class="visuallyhidden">Google Plus</span>
            </button>
          </div>

        </footer>
      </main>
      <div class="mdl-layout__obfuscator"></div>
    </div>
    <script src="{{STATIC_URL}}md/material.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="{{STATIC_URL}}javascripts/likes_tarea.js" type="text/javascript"></script>
    <script src="{{STATIC_URL}}javascripts/script.js" type="text/javascript"></script>
    <script src="{{STATIC_URL}}javascripts/denuncias.js" type="text/javascript"></script>
  </body>
</html>

base/templates/index_.html
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="es"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />

  <title>Sigue tu funcionario</title>
  

  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="{{STATIC_URL}}stylesheets/foundation.min.css">
  <link rel="stylesheet" href="{{STATIC_URL}}stylesheets/main.css">
  <link rel="stylesheet" href="{{STATIC_URL}}stylesheets/app.css">
  <link rel="stylesheet" href="{{STATIC_URL}}stylesheets/foundation-icons.css">


  <script src="{{STATIC_URL}}javascripts/modernizr.foundation.js"></script>

  <!-- Google fonts -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic' rel='stylesheet' type='text/css' />

  <!-- IE Fix for HTML5 Tags -->
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>
  <body>


    <div class="twelve columns header_nav_fullwidth">

      <h1 class="titulo"> <img src="https://cdn4.iconfinder.com/data/icons/flat-color-icons/504/fine_print-64.png" alt=""> Sigue tu Funcionario</h1>
      <div class="two columns">
      </div>  


      <div class="eight columns">

      </div>

      <div class="three columns text-right">
        <p>          

          {% if user and not user.is_anonymous %}
            <img src="{{user.profile.photo}}" class="img-profile" > <span class="name-profile">{{ user.get_full_name }}</span> <a href="/logout" class="button radius small">Salir</a>
          {% else %}
            <a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}" class="button radius small">Entrar con Twitter</a>
            <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}" class="button radius small">Entrar con Facebook</a>       
          {% endif %}   
        </p>
      </div>

    </div>

    <!-- END Header -->

    <div style="clear: both"></div>

    <!-- page wrap -->
    <div class="twelve columns">
      <!-- page wrap -->


      <div id="container">      
      {% for item in funcionarios %}  
       <!-- photo -->
       <div class='box photo col2'>
        <a href="#"><img src='{{MEDIA_URL}}{{item.funcionario.fotografia}}' class="img-funcionario" /></a>
        
        <div class="dependencia">{{item.funcionario.dependencia}}</div>      
        <p>{{item.funcionario.nombre}}</p>  
        {% if user and not user.is_anonymous %}    

          {% if item.like != None %}                     
            {% if item.like == True %}              
              <button class="megusta dislike right" like="0" idfuncionario="{{item.funcionario.id}}" id="nomegusta{{item.funcionario.id}}" ><i class="fi-dislike"></i> <span class="texto-megusta" id="cuantonomegusta{{item.funcionario.id}}">{{item.nomegusta}}</span> </button>
              <button class="megusta like-azul right" like="1" idfuncionario="{{item.funcionario.id}}" id="megusta{{item.funcionario.id}}" ><i class="fi-like "></i> <span class="texto-megusta" id="cuantomegusta{{item.funcionario.id}}">{{item.megusta}}</span> </button>                     
            {% else %}                        
              <button class="megusta dislike-rojo right" like="0" idfuncionario="{{item.funcionario.id}}" id="nomegusta{{item.funcionario.id}}" ><i class="fi-dislike"></i> <span class="texto-megusta" id="cuantonomegusta{{item.funcionario.id}}">{{item.nomegusta}}</span> </button>
              <button class="megusta like right" like="1" idfuncionario="{{item.funcionario.id}}" id="megusta{{item.funcionario.id}}" ><i class="fi-like"></i> <span class="texto-megusta" id="cuantomegusta{{item.funcionario.id}}">{{item.megusta}}</span></button>
            {% endif %}
          {% else%}            
            <button class="megusta dislike right" like="0" idfuncionario="{{item.funcionario.id}}" id="nomegusta{{item.funcionario.id}}"><i class="fi-dislike"></i> <span class="texto-megusta" id="cuantonomegusta{{item.funcionario.id}}">{{item.nomegusta}}</span> </button>          
            <button class="megusta like right" like="1" idfuncionario="{{item.funcionario.id}}" id="megusta{{item.funcionario.id}}"><i class="fi-like"></i> <span class="texto-megusta" id="cuantomegusta{{item.funcionario.id}}">{{item.megusta}}</span> </button>
          {% endif %}

        {% else %}
          <button class="dislike right" onclick="javascript:alert('Identificate!!');"   ><i class="fi-dislike"></i> <span class="texto-megusta">{{item.nomegusta}}</span> </button>          
          <button class="like right" onclick="javascript:alert('Identificate!!');"   ><i class="fi-like"></i> <span class="texto-megusta">{{item.megusta}}</span> </button>
        {% endif %}                  
       
      </div>     
      {% endfor %}

    </div> <!-- end Masonry container -->

    <div class="twelve columns">
      <ul id="menu3" class="footer_menu horizontal">

     </ul>
   </div>

  </div>
  <!-- end page wrap) -->
  <!-- Included JS Files (Compressed) -->
  <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
  <script src="{{STATIC_URL}}javascripts/foundation.min.js" type="text/javascript">
  </script>

  <!-- Initialize JS Plugins -->  
  <script src="{{STATIC_URL}}javascripts/app.js" type="text/javascript">
  </script>
  <script src="{{STATIC_URL}}javascripts/likes.js" type="text/javascript">
  </script>
  <!-- Masonry for galleries -->
  <script src="{{STATIC_URL}}javascripts/masonry.js" type="text/javascript">
  </script>
  <script type="{{STATIC_URL}}text/javascript">
//<![CDATA[
$(function(){
  var $container = $('#container');
  $container.imagesLoaded( function(){
    $container.masonry({
      itemSelector : '.box',
      isFitWidth: true,
      isAnimated: true
    });
  });
});
  //]]>
</script>
<!-- END Masonry -->
</body>
</html>

<script type="text/javascript">
   if (window.location.hash == '#_=_') {            
      history.replaceState({}, document.title, "/");
   }
</script>

base/templates/index_aux.html
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="es"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />

  <title>Sigue tu funcionario</title>
  

  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="{{STATIC_URL}}stylesheets/foundation.min.css">
  <link rel="stylesheet" href="{{STATIC_URL}}stylesheets/main.css">
  <link rel="stylesheet" href="{{STATIC_URL}}stylesheets/app.css">
  <link rel="stylesheet" href="{{STATIC_URL}}stylesheets/foundation-icons.css">


  <script src="{{STATIC_URL}}javascripts/modernizr.foundation.js"></script>

  <!-- Google fonts -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic' rel='stylesheet' type='text/css' />

  <!-- IE Fix for HTML5 Tags -->
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>
  <body>


    <div class="twelve columns header_nav_fullwidth">

      <h1 class="titulo"> <img src="https://cdn4.iconfinder.com/data/icons/flat-color-icons/504/fine_print-64.png" alt=""> Sigue tu Funcionario</h1>
      <div class="two columns">
      </div>  


      <div class="eight columns">

      </div>

      <div class="three columns text-right">
        <p>          

          {% if user and not user.is_anonymous %}
            <img src="{{user.profile.photo}}" class="img-profile" > <span class="name-profile">{{ user.get_full_name }}</span> <a href="/logout" class="button radius small">Salir</a>
          {% else %}
            <a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}" class="button radius small">Entrar con Twitter</a>
            <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}" class="button radius small">Entrar con Facebook</a>       
          {% endif %}   
        </p>
      </div>

    </div>

    <!-- END Header -->

    <div style="clear: both"></div>

    <!-- page wrap -->
    <div class="twelve columns">
      <!-- page wrap -->


      <div id="container">      
      {% for item in funcionarios %}  
       <!-- photo -->
       <div class='box photo col2'>
        <a href="#"><img src='{{MEDIA_URL}}{{item.funcionario.fotografia}}' class="img-funcionario" /></a>
        
        <div class="dependencia">{{item.funcionario.dependencia}}</div>      
        <p>{{item.funcionario.nombre}}</p>  
        {% if user and not user.is_anonymous %}
          
          {% if item.like == True %}              
            {{item.like}}
          {%endif%}
          {% if item.funcionario.funcionariomegusta_set.all.0.usuario.id|add:"0" = user.id %}           
            {% if item.funcionario.funcionariomegusta_set.all.0.megusta == True %}              
              <button class="megusta dislike right" like="0" idfuncionario="{{item.funcionario.id}}" ><i class="fi-dislike"></i> <span class="texto-megusta">{{item.nomegusta}}</span> </button>
              <button class="megusta like-azul right" like="1" idfuncionario="{{item.funcionario.id}}"  ><i class="fi-like "></i> <span class="texto-megusta">{{item.megusta}}</span> </button>                     
            {% else %}                        
              <button class="megusta dislike-rojo right" like="0" idfuncionario="{{item.funcionario.id}}" ><i class="fi-dislike"></i> <span class="texto-megusta">{{item.nomegusta}}</span> </button>
              <button class="megusta like right" like="1" idfuncionario="{{item.funcionario.id}}" ><i class="fi-like"></i> <span class="texto-megusta">{{item.megusta}}</span></button>
            {% endif %}
          {% else%}            
            <button class="megusta dislike right" like="0" idfuncionario="{{item.funcionario.id}}" ><i class="fi-dislike"></i> <span class="texto-megusta">{{item.nomegusta}}</span> </button>          
            <button class="megusta like right" like="1" idfuncionario="{{item.funcionario.id}}" ><i class="fi-like"></i> <span class="texto-megusta">{{item.megusta}}</span> </button>
          {% endif %}

        {% else %}
          <button class="dislike right" onclick="javascript:alert('Identificate!!');"   ><i class="fi-dislike"></i> <span class="texto-megusta">{{item.nomegusta}}</span> </button>          
          <button class="like right" onclick="javascript:alert('Identificate!!');"   ><i class="fi-like"></i> <span class="texto-megusta">{{item.megusta}}</span> </button>
        {% endif %}                  
       
      </div>     
      {% endfor %}

    </div> <!-- end Masonry container -->

    <div class="twelve columns">
      <ul id="menu3" class="footer_menu horizontal">

     </ul>
   </div>

  </div>
  <!-- end page wrap) -->
  <!-- Included JS Files (Compressed) -->
  <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
  <script src="{{STATIC_URL}}javascripts/foundation.min.js" type="text/javascript">
  </script>

  <!-- Initialize JS Plugins -->  
  <script src="{{STATIC_URL}}javascripts/app.js" type="text/javascript">
  </script>
  <script src="{{STATIC_URL}}javascripts/likes.js" type="text/javascript">
  </script>
  <!-- Masonry for galleries -->
  <script src="{{STATIC_URL}}javascripts/masonry.js" type="text/javascript">
  </script>
  <script type="{{STATIC_URL}}text/javascript">
//<![CDATA[
$(function(){
  var $container = $('#container');
  $container.imagesLoaded( function(){
    $container.masonry({
      itemSelector : '.box',
      isFitWidth: true,
      isAnimated: true
    });
  });
});
  //]]>
</script>
<!-- END Masonry -->
</body>
</html>

<script type="text/javascript">
   if (window.location.hash == '#_=_') {            
      history.replaceState({}, document.title, "/");
   }
</script>

base/templates/lista_denuncias.html
<!-- Denuncias -->
{% for denuncia in denuncias %}
<div class="comment mdl-color-text--grey-700">
  <header class="comment__header">
    <img src="{{denuncia.usuario.profile.photo}}" class="comment__avatar">

    <div class="comment__author">
      <strong>{{denuncia.usuario}}</strong>
      <span>{{denuncia.fecha|date:'d-m-Y H:i'}}</span>
    </div>
  </header>
  <div class="comment__text">{{denuncia}}</div>
</div>
{% endfor %}